use_frameworks!

platform :ios, '10.0'

target 'GGXOfflineWebCache_Example' do
  pod 'GGXOfflineWebCache', :path => '../'

  target 'GGXOfflineWebCache_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
