source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
#source 'https://github.com/cocoapods/specs.git'

use_frameworks!

platform :ios, '13.0'

target 'GGXOfflineWebCache_Example' do
  pod 'GGXOfflineWebCache', :path => '../'

#  pod 'GGXSwiftExtension', :path => '/Users/gaoguangxiao/Documents/GitHub/ggxswiftexten'
#  pod 'ZKBaseSwiftProject',:path => '/Users/gaoguangxiao/Documents/GitHub/ZKBaseSwiftProject'
#  pod 'GXTaskDownload', :path => '/Users/gaoguangxiao/Documents/GitHub/GXTaskDownload'
#   pod 'PTDebugView',:path => '~/Documents/GitHub/PTDebugView'

  pod 'ZKBaseSwiftProject'
  
  target 'GGXOfflineWebCache_Tests' do
    inherit! :search_paths
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end

#post_install do |installer|
#    installer.generated_projects.each do |project|
#          project.targets.each do |target|
#              target.build_configurations.each do |config|
#                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
#               end
#          end
#   end
#end
